actions:
  1:
    action: delete_logs
    description: "delete logs"
    options:
      ignore_empty_list: True
      disable_action: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days 
      unit_count: 1
      exclude:
    - filtertype: kibana
      exclude: True
  2:
    action: delete_elastic_monitor
    description: "delete mornitor"
    options:
      ignore_empty_list: True
      disable_action: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: .monitoring-es
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 3
      exclude:
    - filtertype: kibana
      exclude: True 
