actions:
  1:
    action: close
    description: "close logs"
    options:
      ignore_empty_list: True
      disable_action: False 
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 1
      exclude:
  2:
    action: delete_indices 
    description: "delete logs"
    options:
      ignore_empty_list: True
      disable_action: False 
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days 
      unit_count: 2
      exclude:
    - filtertype: opened
      exclude: True
  3:
    action: close
    description: "close other"
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 2
      exclude:
    - filtertype: kibana
      exclude: True
  4:
    action: delete_indices
    description: "delete monitor logs"
    options:
      ignore_empty_list: True
      disable_action: False 
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 3
      exclude:
    - filtertype: opened
      exclude: True
